trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Java..."
    sudo apt-get update
    sudo apt-get install openjdk-17-jdk -y
    java -version
  displayName: 'Install Java 17'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-B'
    goals: 'clean install'

- script: |
    echo "Running tests..."
    mvn test
  displayName: 'Run tests'
